-- TechEvents Peru - Phase 9 notification delivery tracking
-- Run once in RECOPILAR_LINK > SQL Editor before enabling the daily workflow.

begin;

create table if not exists public.notification_deliveries (
    id bigint generated by default as identity primary key,
    recipient_hash char(64) not null,
    event_id uuid not null references public.events (id) on delete cascade,
    digest_date date not null,
    status text not null default 'pending',
    attempted_at timestamptz not null default now(),
    sent_at timestamptz,
    error_message text,
    constraint notification_deliveries_recipient_event_unique
        unique (recipient_hash, event_id),
    constraint notification_deliveries_recipient_hash_check
        check (recipient_hash ~ '^[0-9a-f]{64}$'),
    constraint notification_deliveries_status_check
        check (status in ('pending', 'sent', 'failed')),
    constraint notification_deliveries_sent_at_check
        check ((status = 'sent' and sent_at is not null) or status <> 'sent')
);

create index if not exists notification_deliveries_recipient_status_idx
    on public.notification_deliveries (recipient_hash, status);
create index if not exists notification_deliveries_digest_date_idx
    on public.notification_deliveries (digest_date desc);

alter table public.notification_deliveries enable row level security;
revoke all on table public.notification_deliveries from anon, authenticated;
revoke all on sequence public.notification_deliveries_id_seq from anon, authenticated;

comment on table public.notification_deliveries is
    'Backend-only per-recipient event delivery log used to prevent duplicate digests.';
comment on column public.notification_deliveries.recipient_hash is
    'SHA-256 of the normalized recipient email; the address itself is never stored.';

commit;

