-- TechEvents Peru - Phase 1 database schema
-- Run this entire file once in RECOPILAR_LINK > SQL Editor.

begin;

create extension if not exists pgcrypto;

create table if not exists public.event_sources (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    base_url text not null,
    source_type text not null,
    connector text not null,
    enabled boolean not null default true,
    priority smallint not null default 100,
    last_scraped_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint event_sources_name_unique unique (name),
    constraint event_sources_connector_unique unique (connector),
    constraint event_sources_source_type_check
        check (source_type in ('API', 'RSS', 'ICAL', 'JSON', 'HTML', 'SCRAPER')),
    constraint event_sources_priority_check check (priority >= 0),
    constraint event_sources_base_url_check check (base_url ~ '^https?://')
);

create table if not exists public.events (
    id uuid primary key default gen_random_uuid(),
    title text not null,
    slug text not null,
    description text,
    organization text,
    category text not null default 'Other',
    subcategory text,
    tags text[] not null default '{}',
    event_type text,
    start_date timestamptz not null,
    end_date timestamptz,
    timezone text not null default 'America/Lima',
    modality text not null,
    venue text,
    city text,
    country text,
    latitude numeric(9,6),
    longitude numeric(9,6),
    is_free boolean,
    price numeric(12,2),
    currency char(3),
    registration_url text,
    source_url text not null,
    image_url text,
    source text not null,
    source_event_id text,
    event_hash char(64) not null,
    status text not null default 'published',
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint events_event_hash_unique unique (event_hash),
    constraint events_event_hash_format_check check (event_hash ~ '^[0-9a-f]{64}$'),
    constraint events_modality_check check (modality in ('in_person', 'virtual', 'hybrid')),
    constraint events_status_check
        check (status in ('draft', 'published', 'postponed', 'cancelled', 'archived')),
    constraint events_dates_check check (end_date is null or end_date >= start_date),
    constraint events_latitude_check check (latitude is null or latitude between -90 and 90),
    constraint events_longitude_check check (longitude is null or longitude between -180 and 180),
    constraint events_price_check check (price is null or price >= 0),
    constraint events_currency_check check (currency is null or currency ~ '^[A-Z]{3}$'),
    constraint events_source_url_check check (source_url ~ '^https?://'),
    constraint events_registration_url_check
        check (registration_url is null or registration_url ~ '^https?://'),
    constraint events_image_url_check check (image_url is null or image_url ~ '^https?://')
);

create unique index if not exists events_source_external_id_unique
    on public.events (source, source_event_id)
    where source_event_id is not null;

create index if not exists events_start_date_idx on public.events (start_date);
create index if not exists events_status_start_date_idx
    on public.events (status, start_date);
create index if not exists events_category_idx on public.events (category);
create index if not exists events_city_idx on public.events (city);
create index if not exists events_modality_idx on public.events (modality);
create index if not exists events_organization_idx on public.events (organization);
create index if not exists events_tags_gin_idx on public.events using gin (tags);

create table if not exists public.scraping_logs (
    id bigint generated by default as identity primary key,
    source_id uuid references public.event_sources (id) on delete set null,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    status text not null default 'running',
    events_found integer not null default 0,
    events_inserted integer not null default 0,
    events_updated integer not null default 0,
    duplicates_found integer not null default 0,
    error_message text,
    constraint scraping_logs_status_check
        check (status in ('running', 'success', 'partial', 'failed')),
    constraint scraping_logs_counts_check check (
        events_found >= 0 and events_inserted >= 0
        and events_updated >= 0 and duplicates_found >= 0
    ),
    constraint scraping_logs_dates_check
        check (finished_at is null or finished_at >= started_at)
);

create index if not exists scraping_logs_source_started_idx
    on public.scraping_logs (source_id, started_at desc);
create index if not exists scraping_logs_status_started_idx
    on public.scraping_logs (status, started_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_events_updated_at on public.events;
create trigger set_events_updated_at
before update on public.events
for each row execute function public.set_updated_at();

drop trigger if exists set_event_sources_updated_at on public.event_sources;
create trigger set_event_sources_updated_at
before update on public.event_sources
for each row execute function public.set_updated_at();

comment on column public.events.event_hash is
    'SHA-256 of normalized title, start time, organization and city.';
comment on column public.events.modality is
    'Stable backend code: in_person, virtual or hybrid; the UI translates it.';

commit;
